name: Release

on:
  workflow_dispatch:
  push:
    branches: [main, alpha, beta, next]

permissions:
  id-token: write  # Required for OIDC token generation

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Get GitHub App Token
      id: token
      uses: SocialGouv/token-bureau@main
      with:
        token-bureau-url: https://token-bureau.fabrique.social.gouv.fr
        audience: socialgouv

    - uses: SocialGouv/actions/autodevops-release@v1
      with:
        github-token: ${{ steps.token.outputs.token }}
        author-name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
        author-email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}

# name: Release

# on:
#   push:
#     branches: [main, alpha, beta, next]

# permissions:
#   id-token: write  # Required for OIDC token generation

# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get GitHub App Token
#         id: token
#         uses: SocialGouv/token-bureau@main
#         with:
#           token-bureau-url: https://token-bureau.fabrique.social.gouv.fr
#           audience: socialgouv
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: "14.x"
#       - name: Semantic Release
#         id: semantic
#         uses: cycjimmy/semantic-release-action@v4
#         with:
#           semantic_version: 17
#           extra_plugins: |
#             @semantic-release/changelog@5.0.1
#             @semantic-release/git@9.0.0
#         env:
#           GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
#           GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
#           GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
#           GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
#           GITHUB_TOKEN: ${{ steps.token.outputs.token }}

#       - name: Push updates to branch for major version
#         if: steps.semantic.outputs.new_release_published == 'true'
#         run: |
#           git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git :refs/tags/v${{steps.semantic.outputs.new_release_major_version}}
#           git tag -f v${{steps.semantic.outputs.new_release_major_version}}
#           git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git v${{steps.semantic.outputs.new_release_major_version}}
#         env:
#           GITHUB_TOKEN: ${{ steps.token.outputs.token }}


  
