on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

name: Tests report action
jobs:
  tests-report:
    runs-on: ubuntu-latest
    name: report action
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - shell: bash
        run: |
          cd report
          yarn
          yarn test
      - shell: bash
        run: |
          cd report/www
          yarn
          SKIP_PREFLIGHT_CHECK=true yarn test
